---
title: "Testing Models - Public Repo"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(logitr)
library(fastDummies)
library(here)
library(tidyverse)
library(maddTools)

load(here::here("models", "mnl.RData")) # Load models

```

# MNL

## MNL Dummy


```{r mnl_dummy}

coef(summary(mnl_dummy))
summary(mnl_dummy)$statTable
mnl_dummy$gradient
eigen(mnl_dummy$hessian)$values

```

## MNL WTP

```{r mnl_wtp, echo=FALSE}

coef(summary(mnl_dummy_WTP))
summary(mnl_dummy_WTP)$statTable
mnl_dummy_WTP$gradient
eigen(mnl_dummy_WTP$hessian)$values

```

## MNL WTP Weighted

```{r mnl_dummy_wtp_weighted}

coef(summary(mnl_dummy_WTP_weighted))
summary(mnl_dummy_WTP_weighted)$statTable
mnl_dummy_WTP_weighted$gradient
eigen(mnl_dummy_WTP_weighted$hessian)$values

```

# MXL

## MXL_dummy

```{r mxl_dummy}

coef(summary(mxl_dummy))
summary(mxl_dummy)$statTable
mxl_dummy$gradient
eigen(mxl_dummy$hessian)$values

```


## MXL WTP

```{r mxl_wtp}

coef(summary(mxl_wtp))
summary(mxl_wtp)$statTable
mxl_wtp$gradient
eigen(mxl_wtp$hessian)$values


```

## MXL WTP Weighted

```{r mxl_wtp_weighted}

coef(summary(mxl_wtp_weighted))
summary(mxl_wtp_weighted)$statTable
mxl_wtp_weighted$gradient
eigen(mxl_wtp_weighted$hessian)$values


```

