---
title: "Testing Models - Public Repo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries and settings
source(here::here('code', '0setup.R'))

# Load models
load(here::here("models", "mxl.RData")) 
load(here::here("models", "mxl_gender.RData"))
load(here::here("models", "mxl_income.RData"))
load(here::here("models", "mxl_v2.RData"))

# Function for printing summary & gradient
print_summary <- function(x) {
  print(summary(x))
  print(matrix(x$gradient))
}
```


# Mixed logit models (MXL)

## MXL Preference

```{r mxl_pref}
print_summary(mxl_pref)
```

## MXL WTP

```{r mxl_wtp}
print_summary(mxl_wtp)
```

## MXL WTP Weighted

```{r mxl_wtp_weighted}
print_summary(mxl_wtp_weighted)
```

# MXL models by gender

## Male 

```{r mxl_wtp_gender_A}
print_summary(mxl_wtp_gender_A)
```

## Female, transgender, non-binary

```{r mxl_wtp_gender_B}
print_summary(mxl_wtp_gender_B)
```

# MXL models by income

## Mid/High Income 

```{r mxl_wtp_income_A}
print_summary(mxl_wtp_income_A)
```

## Low Income

```{r mxl_wtp_income_B}
print_summary(mxl_wtp_income_B)
```

